import type { Metadata } from "next";
import ClientLayout from '../components/layout/ClientLayout';
import { Geist, Geist_Mono } from "next/font/google";

import "../../public/fonts/pretendard.css";
import '../../styles/index.css';
import '../../styles/layout.css';
import '../../styles/board.css';
import '../../styles/board-perm-table.css';
import '../../styles/admin.css';
import '../../styles/gallery.css';
import '../../styles/alerts.css';
import './globals.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
